# Generated by Django 3.2.8 on 2021-10-31 12:00

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Company',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('companyname', models.CharField(max_length=122)),
                ('companyid', models.CharField(max_length=122)),
            ],
        ),
        migrations.CreateModel(
            name='Student',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(max_length=122)),
                ('studentname', models.CharField(max_length=122)),
                ('email', models.CharField(max_length=122)),
                ('branch', models.CharField(max_length=122)),
                ('semester', models.IntegerField()),
                ('precentage', models.DecimalField(decimal_places=2, max_digits=3)),
            ],
        ),
    ]
