# Generated by Django 3.2.8 on 2021-10-31 12:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('homeapp', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='student',
            old_name='precentage',
            new_name='percentage',
        ),
    ]
