# Generated by Django 3.2.8 on 2021-11-01 08:06

import datetime
from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('homeapp', '0002_rename_precentage_student_percentage'),
    ]

    operations = [
        migrations.AddField(
            model_name='company',
            name='branch',
            field=models.CharField(default='', max_length=122),
        ),
        migrations.AddField(
            model_name='company',
            name='interviewdate',
            field=models.DateField(default=datetime.date.today),
        ),
        migrations.AddField(
            model_name='company',
            name='interviewtime',
            field=models.TimeField(default=django.utils.timezone.now),
        ),
        migrations.AddField(
            model_name='company',
            name='minpercentage',
            field=models.DecimalField(decimal_places=3, default=35, max_digits=10),
        ),
        migrations.AddField(
            model_name='company',
            name='minsemester',
            field=models.IntegerField(default=1),
        ),
        migrations.AlterField(
            model_name='student',
            name='percentage',
            field=models.DecimalField(decimal_places=3, max_digits=10),
        ),
    ]
